import { registerSW } from "virtual:pwa-register";

/**
 * Register the service worker generated by vite-plugin-pwa.
 * Uses autoUpdate strategy — new SW activates immediately on update.
 */
export function registerServiceWorker() {
  if (!("serviceWorker" in navigator)) {
    console.info("[SW] Service Worker not supported in this browser.");
    return;
  }

  const updateSW = registerSW({
    onRegisteredSW(swUrl, registration) {
      console.info("[SW] Registered:", swUrl);

      // Check for updates periodically (every 60 minutes)
      if (registration) {
        setInterval(
          () => {
            registration.update();
          },
          60 * 60 * 1000,
        );
      }
    },

    onRegisterError(error) {
      console.error("[SW] Registration failed:", error);
    },

    onNeedRefresh() {
      // Auto-update: new content available, reload to use
      console.info("[SW] New content available, updating...");
      updateSW(true);
    },

    onOfflineReady() {
      console.info("[SW] App ready for offline use.");
    },
  });
}
